In [64]:
# Task 1: Pandas
# Import the dataframe
# Find data types of the columns using inbuilt function
# List all the unique values in the “Department” column and clean the mistake
# Drop missing data/NA data from the column 'Score'
# Rename columns “Date Joined” → “JoinedDate” and “Score” → “PerformanceScore”
# Drop duplicate rows based on the “ID” column, keeping only the first occurrence
# 'Departments' may have extra spaces or inconsistent casing, strip whitespace and capitalize each department name
# Save the new dataframe to csv

# Task 2: Numpy
# Make 1D array of numpy with numbers 10 to 20 (inclusive)
# Make the above array to new array of size (5,2)
# Make new array of shape (5,5) with all elements randomly intialized
# Make a new array of all 1's of size 10

In [65]:
import numpy as np
import pandas as pd

In [66]:
# Import the dataframe
df = pd.read_csv('C:/Users/User 1/Desktop/Ai_Ml_QB/messy_data.csv')

In [67]:
# Find data types of the columns using inbuilt function
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   ID           5 non-null      float64
 1   Name         5 non-null      object 
 2   Age          5 non-null      object 
 3   Date Joined  6 non-null      object 
 4   Score        4 non-null      float64
 5   Department   6 non-null      object 
dtypes: float64(2), object(4)
memory usage: 420.0+ bytes


In [68]:
# List all the unique values in the “Department” column and clean the mistake
df.Department

0      Sales
1      sales
2         HR
3        HR 
4    finance
5    Finance
Name: Department, dtype: object

In [69]:
display(df.head())
print(df.to_string())

ID     Name    Age     Date Joined  Score Department
0  1.0    Alice   TRUE      2021-01-15   88.5      Sales
1  2.0     Bob   FALSE      15/02/2021   92.0      sales
2  2.0  Charlie     40      2021-03-05    NaN         HR
3  NaN     Dave     35  April 10, 2021   85.0        HR 
4  5.0      NaN    NaN      2021.05.01   90.0    finance

    ID     Name    Age     Date Joined  Score Department
0  1.0    Alice   TRUE      2021-01-15   88.5      Sales
1  2.0     Bob   FALSE      15/02/2021   92.0      sales
2  2.0  Charlie     40      2021-03-05    NaN         HR
3  NaN     Dave     35  April 10, 2021   85.0        HR 
4  5.0      NaN    NaN      2021.05.01   90.0    finance
5  6.0      Eve     28      2021-06-01    NaN    Finance


In [70]:
df["Department"].value_counts()

Department
Sales      1
sales      1
HR         1
HR         1
finance    1
Finance    1
Name: count, dtype: int64

In [71]:
df["Department"] = df["Department"].apply(lambda x: x.lower())
df["Department"] = df["Department"].apply(lambda x: x.strip())
df["Department"].value_counts()

Department
sales      2
hr         2
finance    2
Name: count, dtype: int64

In [72]:
# Drop missing data/NA data from the column 'Score'
df.Score

0    88.5
1    92.0
2     NaN
3    85.0
4    90.0
5     NaN
Name: Score, dtype: float64

In [73]:
df.dropna(subset="Score", inplace=True)
df.Score

0    88.5
1    92.0
3    85.0
4    90.0
Name: Score, dtype: float64

In [74]:
# Rename columns “Date Joined” → “JoinedDate” and “Score” → “PerformanceScore”
df.rename(columns={"Date Joined": "JoinedDate", "Score": "PerformanceScore"}, inplace=True)
print(df.to_string())

    ID    Name    Age      JoinedDate  PerformanceScore Department
0  1.0   Alice   TRUE      2021-01-15              88.5      sales
1  2.0    Bob   FALSE      15/02/2021              92.0      sales
3  NaN    Dave     35  April 10, 2021              85.0         hr
4  5.0     NaN    NaN      2021.05.01              90.0    finance


In [75]:
# Drop duplicate rows based on the “ID” column, keeping only the first occurrence
print(df.to_string())

    ID    Name    Age      JoinedDate  PerformanceScore Department
0  1.0   Alice   TRUE      2021-01-15              88.5      sales
1  2.0    Bob   FALSE      15/02/2021              92.0      sales
3  NaN    Dave     35  April 10, 2021              85.0         hr
4  5.0     NaN    NaN      2021.05.01              90.0    finance


In [76]:
df.dropna(subset="ID", inplace=True)
print(df.to_string())

    ID    Name    Age  JoinedDate  PerformanceScore Department
0  1.0   Alice   TRUE  2021-01-15              88.5      sales
1  2.0    Bob   FALSE  15/02/2021              92.0      sales
4  5.0     NaN    NaN  2021.05.01              90.0    finance


In [77]:
# 'Departments' may have extra spaces or inconsistent casing, strip whitespace and capitalize each department name
df["Department"].astype(str)
df["Department"] = df["Department"].apply(lambda x: x.strip() if isinstance(x, str) else np.nan)
display(df.Department)

0      sales
1      sales
4    finance
Name: Department, dtype: object

In [78]:
# Save the new dataframe to csv
new_df = df.to_csv("new_df", index=False)

In [79]:
#  Task 2: Numpy
# Make 1D array of numpy with numbers 10 to 20 (inclusive)
# Make the above array to new array of size (5,2)
# Make new array of shape (5,5) with all elements randomly intialized
# Make a new array of all 1's of size 10

In [80]:
import numpy as np

In [81]:
# Make 1D array of numpy with numbers 10 to 20 (inclusive)
arr_1d = np.arange(10,20)
arr_1d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [88]:
# Make the above array to new array of size (5,2)
arr_1d.reshape(5,2)
arr_1d.shape

(10,)

In [87]:
# Make new array of shape (5,5) with all elements randomly intialized
new_arr_55 = np.random.rand(5,5)
new_arr_55

array([[0.66311639, 0.28481064, 0.40898844, 0.76829142, 0.65610521],
       [0.2102734 , 0.16733862, 0.51948576, 0.79641852, 0.50639997],
       [0.38843568, 0.2865317 , 0.12765515, 0.12199629, 0.70408545],
       [0.72692564, 0.0574829 , 0.78080398, 0.06846951, 0.40085504],
       [0.56984203, 0.04131377, 0.55940992, 0.900496  , 0.84197791]])

In [84]:
# Make a new array of all 1's of size 10
new_arr_once = np.ones(10)
new_arr_once

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])