In [1]:
import numpy as np

In [2]:
i = np.array([1,2,3,4])
print(i)
type(i)

[1 2 3 4]


numpy.ndarray

In [3]:
np.__version__

'2.3.0'

In [4]:
# 0-D array
print(np.array(42))

# 1-D Arrays
# An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
print(np.array([1,2,3,4]))

# 2-D Arrays
# An array that has 1-D arrays as its elements is called a 2-D array.
# These are often used to represent matrix or 2nd order tensors.
# NumPy has a whole sub module dedicated towards matrix operations called numpy.mat
print(np.array([[1,2,3],[4,5,6]]))



42
[1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [5]:
#method
print(np.ones((3,3))) #once(shape)
print(np.zeros(3)) #zeros(shape)
print(np.full((2,2),7)) # full(shape,value)
print(np.random.random((3,2)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0. 0. 0.]
[[7 7]
 [7 7]]
[[0.1093683  0.01281644]
 [0.88574172 0.05267568]
 [0.38402433 0.32026328]]


In [6]:
a = np.array(([1,2],(5,3),(4,6)))
print(a)
print(a.max(),a.min(),a.mean(),a.sum(),a.prod(),a.std())
print(a.mean(axis=0))
print(a.max(axis=0))
print(a.max(axis=1))

[[1 2]
 [5 3]
 [4 6]]
6 1 3.5 21 720 1.707825127659933
[3.33333333 3.66666667]
[5 6]
[2 5 6]


In [7]:
#aggregation functions
'''
Function- Name	        NaN-safe Version	            Description
    np.sum	                np.nansum	            Compute sum of elements
    np.prod	                np.nanprod	            Compute product of elements
    np.mean                 np.nanmean	            Compute mean of elements
    np.std              	np.nanstd           	Compute standard deviation
    np.var	                np.nanvar	            Compute variance
    np.min              	np.nanmin	            Find minimum value
    np.max              	np.nanmax           	Find maximum value
    np.argmin	            np.nanargmin	            Find index of minimum value
    np.argmax           	np.nanargmax	        Find index of maximum value
    np.median	            np.nanmedian	        Compute median of elements
    np.percentile        	np.nanpercentile	    Compute rank-based statistics of elements
    np.any	                N/A	                    Evaluate whether any elements are true
    np.all	                N/A	                    Evaluate whether all elements are true
'''

'\nFunction- Name\t        NaN-safe Version\t            Description\n    np.sum\t                np.nansum\t            Compute sum of elements\n    np.prod\t                np.nanprod\t            Compute product of elements\n    np.mean                 np.nanmean\t            Compute mean of elements\n    np.std              \tnp.nanstd           \tCompute standard deviation\n    np.var\t                np.nanvar\t            Compute variance\n    np.min              \tnp.nanmin\t            Find minimum value\n    np.max              \tnp.nanmax           \tFind maximum value\n    np.argmin\t            np.nanargmin\t            Find index of minimum value\n    np.argmax           \tnp.nanargmax\t        Find index of maximum value\n    np.median\t            np.nanmedian\t        Compute median of elements\n    np.percentile        \tnp.nanpercentile\t    Compute rank-based statistics of elements\n    np.any\t                N/A\t                    Evaluate whether any elements a

In [8]:
a.T

array([[1, 5, 4],
       [2, 3, 6]])

In [9]:
# Flip an array vertically or horizontally with np.flipud() and np.fliplr() respectively:
print("a:- \n",a)
print("flip:- \n",np.flip(a))
print("flipud:- \n",np.flipud(a))
print("fliplr:- \n",np.fliplr(a))

a:- 
 [[1 2]
 [5 3]
 [4 6]]
flip:- 
 [[6 4]
 [3 5]
 [2 1]]
flipud:- 
 [[4 6]
 [5 3]
 [1 2]]
fliplr:- 
 [[2 1]
 [3 5]
 [6 4]]


In [10]:
# Rotate an array 90 degrees counter-clockwise with np.rot90() #k = 1(90), 2(180), 3(270), 4(360-no diff)
print("a:- \n",a)
print("np.ratation:- \n",np.rot90(a,k=1))             # Number of 90 degree rotations

a:- 
 [[1 2]
 [5 3]
 [4 6]]
np.ratation:- 
 [[2 3 6]
 [1 5 4]]


In [11]:
# Shift elements in an array along a given dimension with np.roll():
print("a:- \n",a)
print(np.roll(a= a,
        shift = 1,        # Shift elements 2 positions
        axis = 1))         # In each row

# Leave the axis argument empty to shift on a flattened version of the array (shift across all dimensions):
print(np.roll(a= a,
        shift = 1))        # Shift elements 2 positions


a:- 
 [[1 2]
 [5 3]
 [4 6]]
[[2 1]
 [3 5]
 [6 4]]
[[6 1]
 [2 5]
 [3 4]]


In [12]:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3222222363.py, line 1)

In [13]:
d = np.array((1,2,3,4,5,6))
print(d)
print(d.T)
temp = d.reshape(2,3)
print(temp)
print(temp.reshape(-1))
print(temp.reshape(3,2))
print(temp.T)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# d r c
print(np.ones((5,1,3)))
print()
print(np.ones((4,3,2)))

[[[1. 1. 1.]]

 [[1. 1. 1.]]

 [[1. 1. 1.]]

 [[1. 1. 1.]]

 [[1. 1. 1.]]]

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
noted = np.array([[[1, 1, 1]],[[1, 1, 1]],[[1, 1, 1]],[[1, 1, 1]],[[1, 1, 1]]])
noted

NameError: name 'np' is not defined

In [ ]:
noted.ndim
# noted.shape #returns a tuple with each index having the number of corresponding elements.

NameError: name 'noted' is not defined

In [ ]:
temp = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]],[[5,5,5],[6,6,6]]])
temp

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]],

       [[5, 5, 5],
        [6, 6, 6]]])

In [ ]:
temp.shape

(3, 2, 3)

In [ ]:
#atributes

temp = np.array([[1,2],[3,4]])
print(temp)
print(temp.shape) # (n row, m col)
print(temp.size) # total number of element
print(temp.dtype) # } print(temp.dtype.itemsize)
print(temp.itemsize) # size in bytes of each element of the array
print(temp.data) #buffer containing the actual elements 
print(np.zeros_like(temp)) #Return an array of zeros with the same shape and typeP
print(np.ones_like(temp))

[[1 2]
 [3 4]]
(2, 2)
4
int64
8
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]


In [ ]:
#creating idenity matrix
#eye(shape)
x = np.eye(3,5)
print(x)
x = np.identity(3)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr = np.array([1.9,2.5,4.5])
print(arr.dtype)
int_arr = arr.astype(int)
print(int_arr)
print(int_arr.dtype)

float64
[1 2 4]
int64


In [ ]:
t = np.array([[1,2],[3,4]],dtype = str)
print(t,"\n ---")
t2 = np.ones((2, 3, 4), dtype=np.int16)
print(t2)

[['1' '2']
 ['3' '4']] 
 ---
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [ ]:
# To create sequences of numbers, NumPy provides the arange function which 
# is analogous to the Python built-in range, but returns an array.
t = np.arange(10,31,5)
t

array([10, 15, 20, 25, 30])

In [ ]:
# function linspace that receives as an argument the number of elements that we want
t= np.linspace(0,10,5)  # 5 numbers from 0 to 5 (5 is included)
t

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
from numpy import pi
x = np.linspace(0,2* pi , 100)
print(x)
print("-"*40)
f = np.sin(x) # gives in sie=neific format
print(f)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

In [ ]:
np.fromfunction(lambda i, j: i+j, (2,2), dtype=float)

array([[0., 1.],
       [1., 2.]])

In [ ]:
np.arange(12).reshape(4,3) # we have to give prefect number into the arange()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])