In [64]:
import numpy as np


In [65]:
arr = np.array([1,2,3,4,5], ndmin=5) #
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


In [66]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('2nd element on 1st row: ', arr[0, 1])

print()

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 2])

print()

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('Last element from 2nd dim: ', arr[1, -1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row:  2

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 2nd dim:  10


In [67]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

For i, u, f, S and U we can define size as well.

In [68]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [69]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [70]:
print(arr.astype('f')) # for changing the data type of existing array
print(arr.astype(float)) #if we write full name then don't use ''

[1. 2. 3. 4.]
[1. 2. 3. 4.]


Copy and View

copy owns the data and any changes made to the copy will no affect original array and any changes made on original array will not affact to the copy

view does not own the data and any changes made to the view will affect the original array

array has the attribute base that return none if the array owns the data
in simple, the base attribute refers to the original object

base attribute retuen None if the array owns the data

In [71]:
arr = np.array([[1,2,3],[4,5,6]])
x = arr.copy()
y = arr.view()

arr[0][0] = 4
print(x)
print(y)

print(x.base)
print(y.base)


[[1 2 3]
 [4 5 6]]
[[4 2 3]
 [4 5 6]]
None
[[4 2 3]
 [4 5 6]]


In [72]:
arr_4d = np.array([[[[1, 3], [5, 7]], [[9, 11], [13, 15]]],
                    [[[17, 19], [21, 23]], [[25, 27], [29, 31]]]])

print(arr_4d)
print(arr_4d.shape)  # Output: (2, 2, 2, 2)

for i,j in np.ndenumerate(arr_4d):
    print(i,j)

print(arr_4d[1][1][0][0])

[[[[ 1  3]
   [ 5  7]]

  [[ 9 11]
   [13 15]]]


 [[[17 19]
   [21 23]]

  [[25 27]
   [29 31]]]]
(2, 2, 2, 2)
(0, 0, 0, 0) 1
(0, 0, 0, 1) 3
(0, 0, 1, 0) 5
(0, 0, 1, 1) 7
(0, 1, 0, 0) 9
(0, 1, 0, 1) 11
(0, 1, 1, 0) 13
(0, 1, 1, 1) 15
(1, 0, 0, 0) 17
(1, 0, 0, 1) 19
(1, 0, 1, 0) 21
(1, 0, 1, 1) 23
(1, 1, 0, 0) 25
(1, 1, 0, 1) 27
(1, 1, 1, 0) 29
(1, 1, 1, 1) 31
25


Unknown Dimension

when we have not specify the ecact number for one of the dimension in reshape method then we pass -1 as the value

In [73]:
arr = np.array([1,2,3,4,5,6,7,8,9,])
arr.reshape(3,3,-1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [74]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for i in arr:
    print(i)

print("-"*40)

for x in arr:
    for y in x:
        print(y)


[1 2 3]
[4 5 6]
----------------------------------------
1
2
3
4
5
6


nditer()
this is used to avoid the for loop for the iterartion

In [75]:
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6


We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [76]:
for i in np.nditer(arr, flags = ['buffered'], op_dtypes=[float]):
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0


In [77]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

if we want to find the index of particular element then we use this

In [78]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


Key Differences
np.stack(): Adds a new dimension while stacking arrays together.

np.concatenate(): Joins arrays along an existing axis without adding a new dimension.

np.hstack() (Horizontal Stack) → Joins arrays side-by-side (along columns) without adding a new dimension.

np.vstack() (Vertical Stack) → Stacks arrays on top of each other (along rows) without adding a new dimension.

np.dstack() (Depth Stack) → Adds a new third dimension, stacking along depth (axis=2).

In [83]:
# concatenate() is used to join array and we also use axis in that and by defalut it is 0(col)

arr1 = np.array([[1,2],[3,4]])
print(arr1)
print(arr1.shape)
print("-"*40)

arr2 = np.array([[5,6],[7,8]])
print(arr2)
print(arr2.shape)
print("-"*40)

arr = np.concatenate((arr1,arr2))
print(arr)
print(arr.shape)
print("-"*40)

arr = np.concatenate((arr1,arr2),axis=1)
print(arr)
print(arr.shape)


[[1 2]
 [3 4]]
(2, 2)
----------------------------------------
[[5 6]
 [7 8]]
(2, 2)
----------------------------------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
----------------------------------------
[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


In [86]:
arr1 = np.array([[1,2],[3,4]])
print(arr1)
print(arr1.shape)
print("-"*40)

arr2 = np.array([[5,6],[7,8]])
print(arr2)
print(arr2.shape)
print("-"*40)

arr = np.stack((arr1,arr2))
print(arr)
print(arr.shape)
print("-"*40)

arr = np.stack((arr1,arr2),axis=1)
print(arr)
print(arr.shape)


[[1 2]
 [3 4]]
(2, 2)
----------------------------------------
[[5 6]
 [7 8]]
(2, 2)
----------------------------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
----------------------------------------
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
(2, 2, 2)


In [92]:
arr1 = np.array([[1,2],[3,4]])
print(arr1)
print(arr1.shape)
print("-"*40)

arr2 = np.array([[5,6],[7,8]])
print(arr2)
print(arr2.shape)
print("-"*40)

arr = np.hstack((arr1,arr2))
print(arr)
print(arr.shape)

arr = np.vstack((arr1,arr2))
print(arr)
print(arr.shape)

arr = np.dstack((arr1,arr2))
print(arr)
print(arr.shape)


[[1 2]
 [3 4]]
(2, 2)
----------------------------------------
[[5 6]
 [7 8]]
(2, 2)
----------------------------------------
[[1 2 5 6]
 [3 4 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
(2, 2, 2)
