In [26]:
import pandas as pd

In [27]:
arr = np.array([1,2,np.nan,4,np.nan,6])
print(np.isnan(arr))

[False False  True False  True False]


In [28]:
# np.nan_to_num(arr,nan=value) - default = 0
clean_arr = np.nan_to_num(arr)
print(clean_arr)
clean_arr = np.nan_to_num(arr,nan=100)
print(clean_arr)

[1. 2. 0. 4. 0. 6.]
[  1.   2. 100.   4. 100.   6.]


In [29]:
"""
In NumPy, np.inf and -np.inf represent positive infinity and negative infinity, respectively.

What They Mean?
np.inf (Positive Infinity) is a value greater than any finite number.

-np.inf (Negative Infinity) is smaller than any finite number.
"""

'\nIn NumPy, np.inf and -np.inf represent positive infinity and negative infinity, respectively.\n\nWhat They Mean?\nnp.inf (Positive Infinity) is a value greater than any finite number.\n\n-np.inf (Negative Infinity) is smaller than any finite number.\n'

In [30]:
arr = np.array([1,np.nan ,2,np.inf, 4, -np.inf, 6])
print(np.isinf(arr))

[False False False  True False  True False]


In [31]:
clean_arr = np.nan_to_num(arr,posinf=999,neginf=777)
clean_arr

array([  1.,   0.,   2., 999.,   4., 777.,   6.])