In [196]:
import numpy as np

array aplit

In [197]:
arr = np.array([1,2,3,4,5,6])
arr2 =np.split(arr,3)
print(arr2)
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [198]:
dict = {"CAr": "aa", "bb": "value"}
x = dict.setdefault("cc","zz")
print(dict)  
print(x)  


{'CAr': 'aa', 'bb': 'value', 'cc': 'zz'}
zz


In [199]:
#we can split the array in particular index also
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, [3])
print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [200]:
x = np.where(arr == 4)
print(x)
x = np.where(arr%2 == 0) #even
print(x)
for i in x:
    print(arr[i])

(array([3]),)
(array([1, 3, 5]),)
[2 4 6]


In [201]:
#searchsorted :returns the index where the specified value would be inserted to maintain the search order. 
# uses the binary search and assume that array is sorted

arr = np.array([3,7,10,25])
x = np.searchsorted(arr, 11)
print(x)
 
x = np.searchsorted(arr,11,side='right')
print(x)

3
3


In [202]:
import numpy as np
import timeit

arr = np.array([3, 7, 10, 25, 28,30,31,34,36,70])

# Measure execution time using timeit
execution_time = timeit.timeit(lambda: np.searchsorted(arr, 11), number=100000)
print(f"Execution time for searchsorted: {execution_time} seconds")

# Perform searchsorted operation
x = np.searchsorted(arr, 11)
print(x)  # Output: 3 (where 11 would be inserted)

execution_time = timeit.timeit(lambda: np.searchsorted(arr, 11, side='right'), number=100000)
print(f"Execution time for searchsorted: {execution_time} seconds")


x = np.searchsorted(arr, 11, side='right')
print(x)  # Output: 3 (where 11 would be inserted on the right)


Execution time for searchsorted: 0.23621230002027005 seconds
3
Execution time for searchsorted: 0.2034400999546051 seconds
3


In [203]:
#searchsorted() method assume that the array is soerted if array is not sorted then we have to 
# first sort the array using sort functiion or we can also use the argsort()

#using sort()
arr = np.array([40, 10, 20, 30])
sorted_arr = np.sort(arr)  # Ensure the array is sorted
index = np.searchsorted(sorted_arr, 25)

print(sorted_arr)  # Output: [10, 20, 30, 40]
print(index)  # Output: 2 (where 25 would be inserted)

sorter = np.argsort(arr)  # Get sorting indices
index = np.searchsorted(arr, 25, sorter=sorter)

print(index)  # Output: 2 (referring to sorted order)



[10 20 30 40]
2
2


In [204]:
arr = np.array([[0, 3], [2, 2]])
sorted_indices = np.argsort(arr, axis=0)

print(sorted_indices)
print("-"*40)
print(arr[sorted_indices])


[[0 1]
 [1 0]]
----------------------------------------
[[[0 3]
  [2 2]]

 [[2 2]
  [0 3]]]


In [205]:
# #This happens because:

# When using arr[sorted_indices], NumPy interprets the indices in a broadcasting manner, treating each column separately.

# Instead of giving a sorted array directly, NumPy expands into a higher-dimensional structure.

sorted_arr = arr[sorted_indices, np.arange(arr.shape[1])]
print(sorted_arr)



[[0 2]
 [2 3]]


In [206]:
print(arr.shape[1])
print(np.arange(arr.shape[1]))

2
[0 1]


In [207]:
"""
Absolutely! Let's break down your code manually, step by step, and understand how it runs.

### Your Code:
```python
import numpy as np

arr = np.array([[0, 3], [2, 2]])  # Step 1: Define a 2D NumPy array
sorted_indices = np.argsort(arr, axis=0)  # Step 2: Get sorted row indices column-wise

print(sorted_indices)  # Step 3: Print sorted indices
print("-"*40)  # Step 4: Print a separator
print(arr[sorted_indices, np.arange(arr.shape[1])])  # Step 5: Index and reorder array
```

---

### **Step-by-Step Execution:**

#### **Step 1: Create the NumPy Array**
```python
arr = np.array([[0, 3], 
                [2, 2]])
```
The array looks like:
```
[[0 3]
 [2 2]]
```
Each column will be sorted independently.

---

#### **Step 2: Get Sorted Indices Along Axis 0 (Columns)**
```python
sorted_indices = np.argsort(arr, axis=0)
```
- `argsort()` returns the **row indices** that would sort each column.
- **Sorting column-wise** (axis=0):
  - Column **0** (`[0, 2]`): Sorted order is `[0, 2]`, indices remain `[0, 1]`.
  - Column **1** (`[3, 2]`): Sorted order is `[2, 3]`, indices change to `[1, 0]`.

Output of `sorted_indices`:
```
[[0 1] 
 [1 0]]
```
This tells us:
- **First column (0)**: Row order remains **0 → 1**.
- **Second column (1)**: Row order **flips** (1 → 0).

---

#### **Step 3: Print Sorted Indices**
```python
print(sorted_indices)
```
Displays:
```
[[0 1] 
 [1 0]]
```

---

#### **Step 4: Print a Separator**
```python
print("-" * 40)
```
Outputs:
```
----------------------------------------
```
Just a visual separator in the output.

---

#### **Step 5: Reorder `arr` Using Sorted Indices**
```python
print(arr[sorted_indices, np.arange(arr.shape[1])])
```
Breaking it down:

- **`sorted_indices`** gives the row indices to pick for each column.
- **`np.arange(arr.shape[1])`** ensures we are correctly selecting elements **column-wise**.

🔹 **Step-by-step indexing per column:**
- For **column 0**, row indices are `[0, 1]`, so we pick:
  - `arr[0, 0] = 0`
  - `arr[1, 0] = 2`
  - Result: `[0, 2]`
  
- For **column 1**, row indices are `[1, 0]`, so we pick:
  - `arr[1, 1] = 2`
  - `arr[0, 1] = 3`
  - Result: `[2, 3]`

The **final sorted array** is:
```
[[0 2]
 [2 3]]
```

---

### **Final Output:**
```
[[0 1]
 [1 0]]
----------------------------------------
[[0 2]
 [2 3]]
```

🔹 **Key Learning Points:**
1. `argsort(axis=0)` sorts the **columns** independently.
2. The row indices are used to **reorder elements column-wise**.
3. This ensures correct **column-wise sorting**.

Hope this explanation helps! 🚀 Let me know if anything needs further clarification. 😃

"""

'\nAbsolutely! Let\'s break down your code manually, step by step, and understand how it runs.\n\n### Your Code:\n```python\nimport numpy as np\n\narr = np.array([[0, 3], [2, 2]])  # Step 1: Define a 2D NumPy array\nsorted_indices = np.argsort(arr, axis=0)  # Step 2: Get sorted row indices column-wise\n\nprint(sorted_indices)  # Step 3: Print sorted indices\nprint("-"*40)  # Step 4: Print a separator\nprint(arr[sorted_indices, np.arange(arr.shape[1])])  # Step 5: Index and reorder array\n```\n\n---\n\n### **Step-by-Step Execution:**\n\n#### **Step 1: Create the NumPy Array**\n```python\narr = np.array([[0, 3], \n                [2, 2]])\n```\nThe array looks like:\n```\n[[0 3]\n [2 2]]\n```\nEach column will be sorted independently.\n\n---\n\n#### **Step 2: Get Sorted Indices Along Axis 0 (Columns)**\n```python\nsorted_indices = np.argsort(arr, axis=0)\n```\n- `argsort()` returns the **row indices** that would sort each column.\n- **Sorting column-wise** (axis=0):\n  - Column **0** (`[

In [208]:
# Multiple Values
# To search for more than one value, use an array with the specified values.
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 0])
print(x)

[1 2 0]


In [209]:
x = np.sort(arr)
print(x)

[1 3 5 7]


In [210]:
# reverse using flip()
y=np.flip(x)
print(y)

#reverse using slicing
y = x[::-1]
print(y)

#reverse using negate(-)
y = -np.sort(-x)
print(y)

[7 5 3 1]
[7 5 3 1]
[7 5 3 1]


In [211]:
# filtering array
# 1 - way
arr = np.array([40,41,43,46])
x = [True,False,True,False]
newarr = arr[x]
print(newarr)

# 2- way
# Create an empty list
filter_arr = []

for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

# 3- way
temp = []
for i in arr:
    if i > 42:
        temp.append(i)

print(temp)
for i in temp:
    print(i)


# 4- way
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[40 43]
[False, False, True, True]
[43 46]
[np.int64(43), np.int64(46)]
43
46
[False False  True  True]
[43 46]


Array modification

In [212]:
"""
np.insert(array,index,value,axis=None)
arr - original array
axis = 0 for row-wise
axis = 1 for col-wise
"""

'\nnp.insert(array,index,value,axis=None)\narr - original array\naxis = 0 for row-wise\naxis = 1 for col-wise\n'

In [213]:
import numpy as np
arr= np.array([1,2,223,3,3,5])
newarr = np.insert(arr,2,19009)
newarr

array([    1,     2, 19009,   223,     3,     3,     5])

In [214]:
arr_2d = np.array([[1,2],[3,4]])
new_arr_2d = np.insert(arr_2d, 1, [5,6]) #axis = mendatory
print(new_arr_2d)
new_arr_2d = np.insert(arr_2d, 1, [5,6], axis=0) #axis = mendatory
print(new_arr_2d)
new_arr_2d = np.insert(arr_2d, 1, [5,6], axis=1) #axis = mendatory
print(new_arr_2d)

[1 5 6 2 3 4]
[[1 2]
 [5 6]
 [3 4]]
[[1 5 2]
 [3 6 4]]


In [215]:
arr = np.array([10,20,30])
newarr = np.append(arr,[40,50,60])
print(newarr)

[10 20 30 40 50 60]


In [216]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,6,7])
newarr = np.concatenate((arr1,arr2))
print(newarr)

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
newarr = np.concatenate((arr1,arr2))
print(newarr)


newarr1 = np.concatenate((arr1,arr2),axis = 1) # h stacking
print(newarr1)

[1 2 3 4 6 7]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [217]:
#np.delete(arr,index,axis = None)
arr = np.array([1,2,3,4,5,6])
newarr = np.delete(arr,0)
print(newarr)

arr1 = np.array([[1,2,3],[4,5,6]])
newarr = np.delete(arr1,0,axis=0)
newarr1 = np.delete(arr1,0,axis=1)
print(newarr)
print(newarr1)

[2 3 4 5 6]
[[4 5 6]]
[[2 3]
 [5 6]]


In [218]:
#vstack & hstack
arr1 = np.array([1,2,3])
arr2 = np.array([4,6,7])

print(np.vstack((arr1,arr2))) #vertical stack
print(np.hstack((arr1,arr2))) #horizontally stack


[[1 2 3]
 [4 6 7]]
[1 2 3 4 6 7]


In [219]:
#np.split & np.hsplit() & np.vsplit

arr = np.array([10,20,30,40,50,60])
print(np.split(arr,2))

[array([10, 20, 30]), array([40, 50, 60])]


In [220]:
arr_2d = np.array([[1,2],[3,4]])
print(np.split(arr_2d,1))
print(np.hsplit(arr_2d,1))
print(np.vsplit(arr_2d,1))

[array([[1, 2],
       [3, 4]])]
[array([[1, 2],
       [3, 4]])]
[array([[1, 2],
       [3, 4]])]


In [221]:
l1= [1,2,3]
l2 = [4,5,6]
rs = [x+y for x,y in zip(l1,l2)]
rs

[5, 7, 9]

In [222]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
re = arr1 + arr2
re

array([5, 7, 9])

In [223]:
arr = np.array([2,1,8,2,6,3])
a = np.argsort(arr)
arr[a]

array([1, 2, 2, 3, 6, 8])